version: "3"
services:
  backend:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      - IMPART_ENV
      - IMPART_DEBUG
      - IMPART_PORT=8080
      - IMPART_API_KEY
      - IMPART_REGION
      - IMPART_IOS_NOTIFICATION_ARN
      - IMPART_PROFILE_SCHEMA_PATH=./schemas/json/Profile.json
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - IMPART_DB_HOST=mysql
      - IMPART_DB_PORT=3306
      - IMPART_DB_NAME
      - IMPART_DB_MIGRATION_USERNAME
      - IMPART_DB_MIGRATION_PASSWORD
      - IMPART_DB_USERNAME
      - IMPART_DB_PASSWORD
    entrypoint: ["/app/impart-backend"]
    depends_on:
      - bootstrap-mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 20s
      timeout: 2s
      retries: 3
      start_period: 5s
  mysql:
    image: mysql/mysql-server:5.7
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=impart
      - MYSQL_USER=impart_super
      - MYSQL_PASSWORD=supersecretpassword
      - MYSQL_ROOT_PASSWORD=supersecretpassword
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "/healthcheck.sh" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
  bootstrap-mysql:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_DATABASE=impart
      - MYSQL_USER=impart_super
      - MYSQL_PASSWORD=supersecretpassword
      - CRUD_USER=impart_crud
      - CRUD_PASSWORD=supersecretpassword
      - MYSQL_ROOT_PASSWORD=supersecretpassword
    volumes:
      - $PWD/script:/script
    entrypoint: [ "/script/wait-for-it.sh", "mysql:3306", "-t", "30", "--", "/script/misc/create_users.sh" ]
    depends_on:
      - mysql
volumes:
  mysql-volume: