// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

var TableNames = struct {
	Answer                    string
	Comment                   string
	CommentEdits              string
	CommentReactions          string
	Hive                      string
	HiveAdmins                string
	HiveMembers               string
	NotificationDeviceMapping string
	NotificationSubscriptions string
	NotificationTopic         string
	Pings                     string
	Post                      string
	PostEdits                 string
	PostReactions             string
	PostTag                   string
	Profile                   string
	Question                  string
	QuestionType              string
	Questionnaire             string
	Tag                       string
	User                      string
	UserAnswers               string
	UserConfigurations        string
	UserDevices               string
}{
	Answer:                    "answer",
	Comment:                   "comment",
	CommentEdits:              "comment_edits",
	CommentReactions:          "comment_reactions",
	Hive:                      "hive",
	HiveAdmins:                "hive_admins",
	HiveMembers:               "hive_members",
	NotificationDeviceMapping: "notification_device_mapping",
	NotificationSubscriptions: "notification_subscriptions",
	NotificationTopic:         "notification_topic",
	Pings:                     "pings",
	Post:                      "post",
	PostEdits:                 "post_edits",
	PostReactions:             "post_reactions",
	PostTag:                   "post_tag",
	Profile:                   "profile",
	Question:                  "question",
	QuestionType:              "question_type",
	Questionnaire:             "questionnaire",
	Tag:                       "tag",
	User:                      "user",
	UserAnswers:               "user_answers",
	UserConfigurations:        "user_configurations",
	UserDevices:               "user_devices",
}
