// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// UserDevice is an object representing the database table.
type UserDevice struct {
	Token          string    `boil:"token" json:"token" toml:"token" yaml:"token"`
	ImpartWealthID string    `boil:"impart_wealth_id" json:"impart_wealth_id" toml:"impart_wealth_id" yaml:"impart_wealth_id"`
	DeviceID       string    `boil:"device_id" json:"device_id" toml:"device_id" yaml:"device_id"`
	AppVersion     string    `boil:"app_version" json:"app_version" toml:"app_version" yaml:"app_version"`
	DeviceName     string    `boil:"device_name" json:"device_name" toml:"device_name" yaml:"device_name"`
	DeviceVersion  string    `boil:"device_version" json:"device_version" toml:"device_version" yaml:"device_version"`
	CreatedAt      time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt      time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	DeletedAt      null.Time `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`
	DeviceToken    string    `boil:"device_token" json:"device_token" toml:"device_token" yaml:"device_token"`

	R *userDeviceR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userDeviceL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserDeviceColumns = struct {
	Token          string
	ImpartWealthID string
	DeviceID       string
	AppVersion     string
	DeviceName     string
	DeviceVersion  string
	CreatedAt      string
	UpdatedAt      string
	DeletedAt      string
	DeviceToken    string
}{
	Token:          "token",
	ImpartWealthID: "impart_wealth_id",
	DeviceID:       "device_id",
	AppVersion:     "app_version",
	DeviceName:     "device_name",
	DeviceVersion:  "device_version",
	CreatedAt:      "created_at",
	UpdatedAt:      "updated_at",
	DeletedAt:      "deleted_at",
	DeviceToken:    "device_token",
}

var UserDeviceTableColumns = struct {
	Token          string
	ImpartWealthID string
	DeviceID       string
	AppVersion     string
	DeviceName     string
	DeviceVersion  string
	CreatedAt      string
	UpdatedAt      string
	DeletedAt      string
	DeviceToken    string
}{
	Token:          "user_devices.token",
	ImpartWealthID: "user_devices.impart_wealth_id",
	DeviceID:       "user_devices.device_id",
	AppVersion:     "user_devices.app_version",
	DeviceName:     "user_devices.device_name",
	DeviceVersion:  "user_devices.device_version",
	CreatedAt:      "user_devices.created_at",
	UpdatedAt:      "user_devices.updated_at",
	DeletedAt:      "user_devices.deleted_at",
	DeviceToken:    "user_devices.device_token",
}

// Generated where

var UserDeviceWhere = struct {
	Token          whereHelperstring
	ImpartWealthID whereHelperstring
	DeviceID       whereHelperstring
	AppVersion     whereHelperstring
	DeviceName     whereHelperstring
	DeviceVersion  whereHelperstring
	CreatedAt      whereHelpertime_Time
	UpdatedAt      whereHelpertime_Time
	DeletedAt      whereHelpernull_Time
	DeviceToken    whereHelperstring
}{
	Token:          whereHelperstring{field: "`user_devices`.`token`"},
	ImpartWealthID: whereHelperstring{field: "`user_devices`.`impart_wealth_id`"},
	DeviceID:       whereHelperstring{field: "`user_devices`.`device_id`"},
	AppVersion:     whereHelperstring{field: "`user_devices`.`app_version`"},
	DeviceName:     whereHelperstring{field: "`user_devices`.`device_name`"},
	DeviceVersion:  whereHelperstring{field: "`user_devices`.`device_version`"},
	CreatedAt:      whereHelpertime_Time{field: "`user_devices`.`created_at`"},
	UpdatedAt:      whereHelpertime_Time{field: "`user_devices`.`updated_at`"},
	DeletedAt:      whereHelpernull_Time{field: "`user_devices`.`deleted_at`"},
	DeviceToken:    whereHelperstring{field: "`user_devices`.`device_token`"},
}

// UserDeviceRels is where relationship names are stored.
var UserDeviceRels = struct {
	ImpartWealth               string
	NotificationDeviceMappings string
}{
	ImpartWealth:               "ImpartWealth",
	NotificationDeviceMappings: "NotificationDeviceMappings",
}

// userDeviceR is where relationships are stored.
type userDeviceR struct {
	ImpartWealth               *User                          `boil:"ImpartWealth" json:"ImpartWealth" toml:"ImpartWealth" yaml:"ImpartWealth"`
	NotificationDeviceMappings NotificationDeviceMappingSlice `boil:"NotificationDeviceMappings" json:"NotificationDeviceMappings" toml:"NotificationDeviceMappings" yaml:"NotificationDeviceMappings"`
}

// NewStruct creates a new relationship struct
func (*userDeviceR) NewStruct() *userDeviceR {
	return &userDeviceR{}
}

// userDeviceL is where Load methods for each relationship are stored.
type userDeviceL struct{}

var (
	userDeviceAllColumns            = []string{"token", "impart_wealth_id", "device_id", "app_version", "device_name", "device_version", "created_at", "updated_at", "deleted_at", "device_token"}
	userDeviceColumnsWithoutDefault = []string{"token", "impart_wealth_id", "device_id", "app_version", "device_name", "device_version", "created_at", "updated_at", "deleted_at", "device_token"}
	userDeviceColumnsWithDefault    = []string{}
	userDevicePrimaryKeyColumns     = []string{"token"}
)

type (
	// UserDeviceSlice is an alias for a slice of pointers to UserDevice.
	// This should almost always be used instead of []UserDevice.
	UserDeviceSlice []*UserDevice
	// UserDeviceHook is the signature for custom UserDevice hook methods
	UserDeviceHook func(context.Context, boil.ContextExecutor, *UserDevice) error

	userDeviceQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userDeviceType                 = reflect.TypeOf(&UserDevice{})
	userDeviceMapping              = queries.MakeStructMapping(userDeviceType)
	userDevicePrimaryKeyMapping, _ = queries.BindMapping(userDeviceType, userDeviceMapping, userDevicePrimaryKeyColumns)
	userDeviceInsertCacheMut       sync.RWMutex
	userDeviceInsertCache          = make(map[string]insertCache)
	userDeviceUpdateCacheMut       sync.RWMutex
	userDeviceUpdateCache          = make(map[string]updateCache)
	userDeviceUpsertCacheMut       sync.RWMutex
	userDeviceUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var userDeviceBeforeInsertHooks []UserDeviceHook
var userDeviceBeforeUpdateHooks []UserDeviceHook
var userDeviceBeforeDeleteHooks []UserDeviceHook
var userDeviceBeforeUpsertHooks []UserDeviceHook

var userDeviceAfterInsertHooks []UserDeviceHook
var userDeviceAfterSelectHooks []UserDeviceHook
var userDeviceAfterUpdateHooks []UserDeviceHook
var userDeviceAfterDeleteHooks []UserDeviceHook
var userDeviceAfterUpsertHooks []UserDeviceHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserDevice) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userDeviceBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserDevice) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userDeviceBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserDevice) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userDeviceBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserDevice) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userDeviceBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserDevice) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userDeviceAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserDevice) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userDeviceAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserDevice) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userDeviceAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserDevice) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userDeviceAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserDevice) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userDeviceAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserDeviceHook registers your hook function for all future operations.
func AddUserDeviceHook(hookPoint boil.HookPoint, userDeviceHook UserDeviceHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		userDeviceBeforeInsertHooks = append(userDeviceBeforeInsertHooks, userDeviceHook)
	case boil.BeforeUpdateHook:
		userDeviceBeforeUpdateHooks = append(userDeviceBeforeUpdateHooks, userDeviceHook)
	case boil.BeforeDeleteHook:
		userDeviceBeforeDeleteHooks = append(userDeviceBeforeDeleteHooks, userDeviceHook)
	case boil.BeforeUpsertHook:
		userDeviceBeforeUpsertHooks = append(userDeviceBeforeUpsertHooks, userDeviceHook)
	case boil.AfterInsertHook:
		userDeviceAfterInsertHooks = append(userDeviceAfterInsertHooks, userDeviceHook)
	case boil.AfterSelectHook:
		userDeviceAfterSelectHooks = append(userDeviceAfterSelectHooks, userDeviceHook)
	case boil.AfterUpdateHook:
		userDeviceAfterUpdateHooks = append(userDeviceAfterUpdateHooks, userDeviceHook)
	case boil.AfterDeleteHook:
		userDeviceAfterDeleteHooks = append(userDeviceAfterDeleteHooks, userDeviceHook)
	case boil.AfterUpsertHook:
		userDeviceAfterUpsertHooks = append(userDeviceAfterUpsertHooks, userDeviceHook)
	}
}

// One returns a single userDevice record from the query.
func (q userDeviceQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserDevice, error) {
	o := &UserDevice{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: failed to execute a one query for user_devices")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all UserDevice records from the query.
func (q userDeviceQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserDeviceSlice, error) {
	var o []*UserDevice

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbmodels: failed to assign all query results to UserDevice slice")
	}

	if len(userDeviceAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all UserDevice records in the query.
func (q userDeviceQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to count user_devices rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q userDeviceQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: failed to check if user_devices exists")
	}

	return count > 0, nil
}

// ImpartWealth pointed to by the foreign key.
func (o *UserDevice) ImpartWealth(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`impart_wealth_id` = ?", o.ImpartWealthID),
		qmhelper.WhereIsNull("deleted_at"),
	}

	queryMods = append(queryMods, mods...)

	query := Users(queryMods...)
	queries.SetFrom(query.Query, "`user`")

	return query
}

// NotificationDeviceMappings retrieves all the notification_device_mapping's NotificationDeviceMappings with an executor.
func (o *UserDevice) NotificationDeviceMappings(mods ...qm.QueryMod) notificationDeviceMappingQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`notification_device_mapping`.`user_device_id`=?", o.Token),
	)

	query := NotificationDeviceMappings(queryMods...)
	queries.SetFrom(query.Query, "`notification_device_mapping`")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"`notification_device_mapping`.*"})
	}

	return query
}

// LoadImpartWealth allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userDeviceL) LoadImpartWealth(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserDevice interface{}, mods queries.Applicator) error {
	var slice []*UserDevice
	var object *UserDevice

	if singular {
		object = maybeUserDevice.(*UserDevice)
	} else {
		slice = *maybeUserDevice.(*[]*UserDevice)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &userDeviceR{}
		}
		args = append(args, object.ImpartWealthID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userDeviceR{}
			}

			for _, a := range args {
				if a == obj.ImpartWealthID {
					continue Outer
				}
			}

			args = append(args, obj.ImpartWealthID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`user`),
		qm.WhereIn(`user.impart_wealth_id in ?`, args...),
		qmhelper.WhereIsNull(`user.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for user")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for user")
	}

	if len(userDeviceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ImpartWealth = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.ImpartWealthUserDevices = append(foreign.R.ImpartWealthUserDevices, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ImpartWealthID == foreign.ImpartWealthID {
				local.R.ImpartWealth = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.ImpartWealthUserDevices = append(foreign.R.ImpartWealthUserDevices, local)
				break
			}
		}
	}

	return nil
}

// LoadNotificationDeviceMappings allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (userDeviceL) LoadNotificationDeviceMappings(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserDevice interface{}, mods queries.Applicator) error {
	var slice []*UserDevice
	var object *UserDevice

	if singular {
		object = maybeUserDevice.(*UserDevice)
	} else {
		slice = *maybeUserDevice.(*[]*UserDevice)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &userDeviceR{}
		}
		args = append(args, object.Token)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userDeviceR{}
			}

			for _, a := range args {
				if a == obj.Token {
					continue Outer
				}
			}

			args = append(args, obj.Token)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`notification_device_mapping`),
		qm.WhereIn(`notification_device_mapping.user_device_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load notification_device_mapping")
	}

	var resultSlice []*NotificationDeviceMapping
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice notification_device_mapping")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on notification_device_mapping")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for notification_device_mapping")
	}

	if len(notificationDeviceMappingAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.NotificationDeviceMappings = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &notificationDeviceMappingR{}
			}
			foreign.R.UserDevice = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.Token == foreign.UserDeviceID {
				local.R.NotificationDeviceMappings = append(local.R.NotificationDeviceMappings, foreign)
				if foreign.R == nil {
					foreign.R = &notificationDeviceMappingR{}
				}
				foreign.R.UserDevice = local
				break
			}
		}
	}

	return nil
}

// SetImpartWealth of the userDevice to the related item.
// Sets o.R.ImpartWealth to related.
// Adds o to related.R.ImpartWealthUserDevices.
func (o *UserDevice) SetImpartWealth(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `user_devices` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"impart_wealth_id"}),
		strmangle.WhereClause("`", "`", 0, userDevicePrimaryKeyColumns),
	)
	values := []interface{}{related.ImpartWealthID, o.Token}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ImpartWealthID = related.ImpartWealthID
	if o.R == nil {
		o.R = &userDeviceR{
			ImpartWealth: related,
		}
	} else {
		o.R.ImpartWealth = related
	}

	if related.R == nil {
		related.R = &userR{
			ImpartWealthUserDevices: UserDeviceSlice{o},
		}
	} else {
		related.R.ImpartWealthUserDevices = append(related.R.ImpartWealthUserDevices, o)
	}

	return nil
}

// AddNotificationDeviceMappings adds the given related objects to the existing relationships
// of the user_device, optionally inserting them as new records.
// Appends related to o.R.NotificationDeviceMappings.
// Sets related.R.UserDevice appropriately.
func (o *UserDevice) AddNotificationDeviceMappings(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*NotificationDeviceMapping) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.UserDeviceID = o.Token
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `notification_device_mapping` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"user_device_id"}),
				strmangle.WhereClause("`", "`", 0, notificationDeviceMappingPrimaryKeyColumns),
			)
			values := []interface{}{o.Token, rel.MapID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.UserDeviceID = o.Token
		}
	}

	if o.R == nil {
		o.R = &userDeviceR{
			NotificationDeviceMappings: related,
		}
	} else {
		o.R.NotificationDeviceMappings = append(o.R.NotificationDeviceMappings, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &notificationDeviceMappingR{
				UserDevice: o,
			}
		} else {
			rel.R.UserDevice = o
		}
	}
	return nil
}

// UserDevices retrieves all the records using an executor.
func UserDevices(mods ...qm.QueryMod) userDeviceQuery {
	mods = append(mods, qm.From("`user_devices`"), qmhelper.WhereIsNull("`user_devices`.`deleted_at`"))
	return userDeviceQuery{NewQuery(mods...)}
}

// FindUserDevice retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserDevice(ctx context.Context, exec boil.ContextExecutor, token string, selectCols ...string) (*UserDevice, error) {
	userDeviceObj := &UserDevice{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `user_devices` where `token`=? and `deleted_at` is null", sel,
	)

	q := queries.Raw(query, token)

	err := q.Bind(ctx, exec, userDeviceObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodels: unable to select from user_devices")
	}

	if err = userDeviceObj.doAfterSelectHooks(ctx, exec); err != nil {
		return userDeviceObj, err
	}

	return userDeviceObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserDevice) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbmodels: no user_devices provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userDeviceColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userDeviceInsertCacheMut.RLock()
	cache, cached := userDeviceInsertCache[key]
	userDeviceInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userDeviceAllColumns,
			userDeviceColumnsWithDefault,
			userDeviceColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userDeviceType, userDeviceMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userDeviceType, userDeviceMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `user_devices` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `user_devices` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `user_devices` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, userDevicePrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to insert into user_devices")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.Token,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to populate default values for user_devices")
	}

CacheNoHooks:
	if !cached {
		userDeviceInsertCacheMut.Lock()
		userDeviceInsertCache[key] = cache
		userDeviceInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the UserDevice.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserDevice) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	userDeviceUpdateCacheMut.RLock()
	cache, cached := userDeviceUpdateCache[key]
	userDeviceUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userDeviceAllColumns,
			userDevicePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbmodels: unable to update user_devices, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `user_devices` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, userDevicePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userDeviceType, userDeviceMapping, append(wl, userDevicePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update user_devices row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by update for user_devices")
	}

	if !cached {
		userDeviceUpdateCacheMut.Lock()
		userDeviceUpdateCache[key] = cache
		userDeviceUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q userDeviceQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all for user_devices")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected for user_devices")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserDeviceSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbmodels: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userDevicePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `user_devices` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, userDevicePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to update all in userDevice slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to retrieve rows affected all in update all userDevice")
	}
	return rowsAff, nil
}

var mySQLUserDeviceUniqueColumns = []string{
	"token",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UserDevice) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("dbmodels: no user_devices provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userDeviceColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLUserDeviceUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userDeviceUpsertCacheMut.RLock()
	cache, cached := userDeviceUpsertCache[key]
	userDeviceUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			userDeviceAllColumns,
			userDeviceColumnsWithDefault,
			userDeviceColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			userDeviceAllColumns,
			userDevicePrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("dbmodels: unable to upsert user_devices, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`user_devices`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `user_devices` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(userDeviceType, userDeviceMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userDeviceType, userDeviceMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to upsert for user_devices")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(userDeviceType, userDeviceMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to retrieve unique values for user_devices")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to populate default values for user_devices")
	}

CacheNoHooks:
	if !cached {
		userDeviceUpsertCacheMut.Lock()
		userDeviceUpsertCache[key] = cache
		userDeviceUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single UserDevice record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserDevice) Delete(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if o == nil {
		return 0, errors.New("dbmodels: no UserDevice provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	var (
		sql  string
		args []interface{}
	)
	if hardDelete {
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userDevicePrimaryKeyMapping)
		sql = "DELETE FROM `user_devices` WHERE `token`=?"
	} else {
		currTime := time.Now().In(boil.GetLocation())
		o.DeletedAt = null.TimeFrom(currTime)
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE `user_devices` SET %s WHERE `token`=?",
			strmangle.SetParamNames("`", "`", 0, wl),
		)
		valueMapping, err := queries.BindMapping(userDeviceType, userDeviceMapping, append(wl, userDevicePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), valueMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete from user_devices")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by delete for user_devices")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q userDeviceQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbmodels: no userDeviceQuery provided for delete all")
	}

	if hardDelete {
		queries.SetDelete(q.Query)
	} else {
		currTime := time.Now().In(boil.GetLocation())
		queries.SetUpdate(q.Query, M{"deleted_at": currTime})
	}

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from user_devices")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for user_devices")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserDeviceSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(userDeviceBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var (
		sql  string
		args []interface{}
	)
	if hardDelete {
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userDevicePrimaryKeyMapping)
			args = append(args, pkeyArgs...)
		}
		sql = "DELETE FROM `user_devices` WHERE " +
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, userDevicePrimaryKeyColumns, len(o))
	} else {
		currTime := time.Now().In(boil.GetLocation())
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userDevicePrimaryKeyMapping)
			args = append(args, pkeyArgs...)
			obj.DeletedAt = null.TimeFrom(currTime)
		}
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE `user_devices` SET %s WHERE "+
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, userDevicePrimaryKeyColumns, len(o)),
			strmangle.SetParamNames("`", "`", 0, wl),
		)
		args = append([]interface{}{currTime}, args...)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: unable to delete all from userDevice slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodels: failed to get rows affected by deleteall for user_devices")
	}

	if len(userDeviceAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserDevice) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserDevice(ctx, exec, o.Token)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserDeviceSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserDeviceSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userDevicePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `user_devices`.* FROM `user_devices` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, userDevicePrimaryKeyColumns, len(*o)) +
		"and `deleted_at` is null"

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbmodels: unable to reload all in UserDeviceSlice")
	}

	*o = slice

	return nil
}

// UserDeviceExists checks if the UserDevice row exists.
func UserDeviceExists(ctx context.Context, exec boil.ContextExecutor, token string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `user_devices` where `token`=? and `deleted_at` is null limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, token)
	}
	row := exec.QueryRowContext(ctx, sql, token)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbmodels: unable to check if user_devices exists")
	}

	return exists, nil
}
