#!/bin/bash

docker-compose down -v --remove-orphans > /dev/null
docker-compose rm -f -v  > /dev/null
docker-compose up -d


function setup_local_env {
  export IMPART_ENV="local"
  export IMPART_DEBUG="true"
  export IMPART_PORT="8080"
  export IMPART_API_KEY="38c31c4a79c04fd102e105f23a7cdcf832e40ad1b1a526ba82da9fe1f86aa5aab288a3f1a85f5edf39478d65c05c6f1328c82de7e1677ca31a4392ab"
  export IMPART_REGION="us-east-2"
  export IMPART_DYNAMO_ENDPOINT="http://localhost:8000"
  export IMPART_IOS_NOTIFICATION_ARN="arn:aws:sns:us-east-1:518740895671:app/APNS_SANDBOX/impart_wealth_dev"
  export IMPART_PROFILE_SCHEMA_PATH="./schemas/json/Profile.json"
}

go build -o impart-backend cmd/server/main.go

setup_local_env
echo "waiting on local create tables..."
docker wait backend_createTables_1 > /dev/null
./impart-backend

docker-compose down -v --remove-orphans  > /dev/null
docker-compose rm -f -v  > /dev/null
